---
title: "Exploratory Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(readxl)
<<<<<<< HEAD:exploratory_analysis.Rmd
=======
```

```{r}

url = "https://www.spotrac.com/mlb/contracts"
read_html(url) |>
  html_table()

>>>>>>> 93fec6e (showing data doc to rest of group):preliminary_analysis.Rmd
```

#### Salaries Dataset

```{r}
salaries = read_excel(
  "data/MLB-Salaries 2000-24.xlsx", 
  sheet = "2022.xls",
  skip = 1) |>
  select(1:4) |>
  rename(position = "Pos'n",
         salary_2022 = "2022.0",
         service_time_yrs = "MLS",
         player = "Player")

salaries
```

#### Batting and Pitching Datasets

```{r}
batting = read_delim("data/2022 MLB Player Stats - Batting.csv", delim = ";",
                     locale = locale(encoding = "latin1")) |>
  janitor::clean_names()
```

```{r}
pitching = read_delim("data/2022 MLB Player Stats - Pitching.csv", delim = ";",
                     locale = locale(encoding = "latin1")) |>
  janitor::clean_names()
```