---
title: "Final_Report_Draft"
author: "Cameron Chesbrough"
date: "2024-11-07"
output: html_document
---

# Motivation

MLB player salaries are growing faster than ever. In 2001, former Seattle Mariners superstar Alex Rodriguez signed a 10-year, \$252 million deal that broke the record for the most lucrative contract in professional sports history. And yet, Rodriguez's deal pales in comparison to the monster contract that current superstar Juan Soto is expected to sign within the next week, which is projected to go for at least 12 years and \$600 million. The skyrocketing salaries don't just apply to the game's most marquee names; since 2003, the average player salary has more than doubled, from \$2.37 million to \$4.98 million for the 2024 season (source: <https://www.statista.com/statistics/236213/mean-salaray-of-players-in-majpr-league-baseball/>). As players become more and more expensive,

The primary goal of our project is to determine whether baseball players -- both batters and pitchers -- are worth their salaries, and whether teams should focus primarily on signing big-money free agents or taking a more egalitarian and young player-heavy approach. More specifically, are advanced statistics such as OPS+ (for hitters) and ERA+ (for pitchers) significantly associated with player salary? Our conclusions could give MLB teams insight into how they can build their rosters to optimize their chances of making the postseason and ultimately winning the World Series.


# Related work

There has been a heated debate over the use of statistics and analytics in the evaluation of player performances and whether the decision to pay players can be aided by these methods. Sabermetrics (add hyperlink in website) is one of the more popular ways of applying statistics to baseball to be an addition to traditional evaluations. The famous movie Moneyball (add hyperlink in website) tells the story of the Oakland Athletic's, an underdog using statistics over traditional evaluations to gain an edge. One of the hopes of our project is to approach some of these same problems from our own perspective.


# Initial questions

Before beginning the project, we set out to potentially answer three primary questions:

1) What collected statistics are most correlated with salary? Are advanced statistics such as ERA closer than simple counts such as strikeouts?

2) Are GMs good at deciding who to give contracts? That is, do the players with the highest salaries have the best performance metrics?

3) Can we predict the salary of a player with a model built from their 2022 statistics?

After conducting an exploratory data analysis, we adjusted our questions into:


# Data

Source, scraping method, cleaning, etc. 

# Exploratory analysis 

Our exploratory data analysis can be grouped into three categories: salary, batting, and pitching. 

Player salaries were highly right-skewed. This was expected, as many players make the league minimum salary of 700,000. The one position group not so heavily right skewed are the Designated Hitters. Similarly, the Designated Hitters had a higher average years of experience. Intuitively this makes sense as teams will want to select the better players for the position. Overall, most players were in their first year of the MLB with 68.2% having 5 or less years of experience. Players with more years of experience seem to get higher salaries, increasing as their years of experience.



# Additional analysis

If you undertake formal statistical analyses, describe these in detail

# Discussion

What were your findings? Are they what you expect? What insights into the data can you make?

Checking to see if committing works.
