<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final Report</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Final_Report_Draft.html">Report</a>
</li>
<li>
  <a href="preliminary_analysis.html">EDA</a>
</li>
<li>
  <a href="conclusion.html">Conclusion</a>
</li>
<li>
  <a href="about_us.html">About the Group</a>
</li>
<li>
  <a href="https://github.com/jl7033/final_project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final Report</h1>

</div>


<div id="motivation" class="section level1">
<h1>Motivation</h1>
<p>MLB player salaries are growing faster than ever. In 2001, former
Seattle Mariners superstar Alex Rodriguez signed a 10-year, $252 million
deal that broke the record for the most lucrative contract in
professional sports history. And yet, Rodriguez’s deal pales in
comparison to the monster contract that current superstar Juan Soto is
expected to sign within the next week, which is projected to go for at
least 12 years and $600 million. The skyrocketing salaries don’t just
apply to the game’s most marquee names; since 2003, the average player
salary has more than doubled, from $2.37 million to $4.98 million for
the 2024 season (<a
href="https://www.statista.com/statistics/236213/mean-salaray-of-players-in-majpr-league-baseball/">source</a>).
As players become more and more expensive and teams face increasingly
harsh luxury tax penalties for exceeding certain payroll thresholds, MLB
teams face important decisions on which, if any, free agents to sign to
long-term, expensive contracts.</p>
<p>The primary goal of our project is to determine whether baseball
players – both batters and pitchers – are worth their salaries, and
whether teams should focus primarily on signing big-money free agents or
taking a more egalitarian and young player-heavy approach. More
specifically, are advanced statistics such as OPS+ (for hitters) and
ERA+ (for pitchers) significantly associated with player salary? Our
conclusions could give MLB teams insight into how they can build their
rosters to optimize their chances of making the postseason and
ultimately winning the World Series.</p>
</div>
<div id="related-work" class="section level1">
<h1>Related work</h1>
<p>There has been a heated debate over the use of statistics and
analytics in the evaluation of player performances and whether the
decision to pay players can be aided by these methods. <a
href="https://sabr.org/sabermetrics">Sabermetrics</a> is one of the more
popular ways of applying statistics to baseball to be an addition to
traditional evaluations. The famous movie <a
href="https://www.imdb.com/title/tt1210166/">Moneyball</a> tells the
story of the Oakland Athletic’s, an underdog using statistics over
traditional evaluations to gain an edge. One of the hopes of our project
is to approach some of these same problems from our own perspective.</p>
</div>
<div id="initial-questions" class="section level1">
<h1>Initial questions</h1>
<p>Before beginning the project, we set out to potentially answer three
primary questions:</p>
<ol style="list-style-type: decimal">
<li><p>What collected statistics are most correlated with salary? Are
advanced statistics such as ERA closer than simple counts such as
strikeouts?</p></li>
<li><p>Are GMs good at deciding who to give contracts? That is, do the
players with the highest salaries have the best performance
metrics?</p></li>
<li><p>Can we predict the salary of a player with a model built from
their 2022 statistics?</p></li>
</ol>
<p>After conducting an exploratory data analysis, we adjusted our
questions into:</p>
<ol style="list-style-type: decimal">
<li><p>Can we construct a model from both counting and advanced
statistics that predicts the salary of a baseball player?</p></li>
<li><p>What player is on the ‘best’ contract? That is, who is the best
player in the MLB in terms outperforming their contract? What player is
on the ‘worst’ contract?</p></li>
</ol>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<div id="salary-data" class="section level3">
<h3>Salary Data</h3>
<pre class="r"><code>salaries = read_excel(
  &quot;data/MLB-Salaries 2000-24.xlsx&quot;, 
  sheet = &quot;2022.xls&quot;,
  skip = 1) |&gt;
  select(1:4) |&gt;
  rename(position = &quot;Pos&#39;n&quot;,
         salary_2022 = &quot;2022.0&quot;,
         service_time_yrs = &quot;MLS&quot;,
         name = &quot;Player&quot;) %&gt;%
  mutate(name = str_split(name, &quot;,&quot;),
         name = map(name, rev),       
         name = map_chr(name, str_c, collapse = &quot; &quot;),
         name = str_trim(name),
         name = str_replace_all(name, &quot;[*#\\.,]&quot;, &quot;&quot;),
         junior = str_detect(name, &quot;Jr&quot;),
         name = if_else(junior == TRUE, str_remove(name, &quot; Jr&quot;), name),
         name = if_else(junior == TRUE, str_c(name, &quot; Jr&quot;), name),
         name = stringi::stri_trans_general(name,id = &quot;Latin-ASCII&quot;)) |&gt;
  select(-junior) %&gt;%
  mutate(simple_position = str_split_i(position, &quot;-&quot;, 1),
         simple_position = fct_relevel(simple_position,
                                       c(&quot;c&quot;, &quot;1b&quot;, &quot;2b&quot;, &quot;3b&quot;, &quot;ss&quot;,
                                         &quot;lf&quot;, &quot;cf&quot;, &quot;rf&quot;, &quot;inf&quot;, &quot;of&quot;,
                                         &quot;dh&quot;, &quot;rhp&quot;, &quot;lhp&quot;)),
         service_time_floor = floor(service_time_yrs),
         experience_group = case_when(service_time_floor &lt;= 2 ~ &quot;0-2 years&quot;,
                                      service_time_floor &gt;= 3 ~ &quot;3+ years&quot;))</code></pre>
</div>
<div id="batting-data" class="section level3">
<h3>Batting Data</h3>
<pre class="r"><code>batting = read_delim(&quot;data/2022 MLB Player Stats - Batting.csv&quot;, delim = &quot;;&quot;,
                     locale = locale(encoding = &quot;latin1&quot;)) |&gt;
  janitor::clean_names() %&gt;%
  group_by(name) |&gt;
  mutate(name_count = n(),
         keep_row = case_when(name_count == 1 ~ TRUE,
                              name_count &gt; 1 &amp; tm == &quot;TOT&quot; ~ TRUE,
                              .default = FALSE)) |&gt;
  filter(keep_row == TRUE) %&gt;%
  mutate(name_count = n(),
         keep_row = case_when(name_count == 1 ~ TRUE,
                              name_count &gt; 1 &amp; lg == &quot;MLB&quot; ~ TRUE,
                              .default = FALSE)) |&gt;
  ungroup() |&gt;
  filter(keep_row == TRUE) %&gt;%
  mutate(name = str_split(name, &quot;\\s+&quot;),
         name = map_chr(name, str_c, collapse = &quot; &quot;),
         name = str_trim(name),
         name = str_replace_all(name, &quot;[*#\\.]&quot;, &quot;&quot;),
         name = stringi::stri_trans_general(name,id = &quot;Latin-ASCII&quot;))

merged_batting &lt;- salaries |&gt;
  mutate(simple_position = str_split_i(position, &quot;-&quot;, 1)) |&gt;
  filter(!simple_position %in% c(&quot;rhp&quot;,&quot;lhp&quot;)) |&gt;
  inner_join(batting, by = &quot;name&quot;) |&gt;
  filter(pa &gt;= 100)

salary_not_in_batting &lt;- anti_join(salaries, batting, by = &quot;name&quot;)
batting_not_in_salary &lt;- anti_join(batting, salaries, by = &quot;name&quot;)</code></pre>
</div>
<div id="pitching-data" class="section level3">
<h3>Pitching Data</h3>
<pre class="r"><code>pitching = read_delim(&quot;data/2022 MLB Player Stats - Pitching.csv&quot;, delim = &quot;;&quot;,
                     locale = locale(encoding = &quot;latin1&quot;)) |&gt;
  janitor::clean_names() %&gt;%
  group_by(name) |&gt;
  mutate(name_count = n(),
         keep_row = case_when(name_count == 1 ~ TRUE,
                              name_count &gt; 1 &amp; tm == &quot;TOT&quot; ~ TRUE,
                              .default = FALSE)) |&gt;
  filter(keep_row == TRUE) %&gt;%
  mutate(name_count = n(),
         keep_row = case_when(name_count == 1 ~ TRUE,
                              name_count &gt; 1 &amp; lg == &quot;MLB&quot; ~ TRUE,
                              .default = FALSE)) |&gt;
  ungroup() |&gt;
  filter(keep_row == TRUE) %&gt;%
  mutate(name = str_split(name, &quot;\\s+&quot;),
         name = map_chr(name, str_c, collapse = &quot; &quot;),
         name = str_trim(name),
         name = str_replace_all(name, &quot;[*#\\.]&quot;, &quot;&quot;),
         name = stringi::stri_trans_general(name,id = &quot;Latin-ASCII&quot;))

merged_pitching &lt;- inner_join(salaries, pitching, by = &quot;name&quot;) |&gt;
  filter(ip &gt;= 20) |&gt;
  separate(ip, into = c(&quot;ip&quot;, &quot;ip_dec&quot;), remove = FALSE, convert = TRUE) |&gt;
  mutate(ip_dec_333 = ifelse(is.na(ip_dec), 0, ip_dec * 333)  ,
         ip_total = paste(ip, ip_dec_333, sep = &quot;.&quot;),
         ip_total = as.numeric(ip_total)) |&gt;
  select(-ip, -ip_dec, -ip_dec_333) |&gt;
  separate(position, into = c(&quot;hand&quot;, &quot;pitcher_type&quot;)) |&gt;
  mutate(pitcher_type = ifelse(is.na(pitcher_type), &quot;r&quot;, pitcher_type)) |&gt;
  filter(hand == &quot;lhp&quot; | hand == &quot;rhp&quot;)

salary_not_in_pitching &lt;- anti_join(salaries, pitching, by = &quot;name&quot;)
pitching_not_in_salary &lt;- anti_join(pitching, salaries, by = &quot;name&quot;)</code></pre>
</div>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory analysis</h1>
<p>Our exploratory data analysis can be grouped into three categories:
salary, batting, and pitching.</p>
<div id="salary-eda" class="section level3">
<h3>Salary EDA</h3>
<p>Player salaries were highly right-skewed. This was expected, as many
players make the league minimum salary of 700,000. The one position
group not so heavily right skewed are the Designated Hitters. Similarly,
the Designated Hitters had a higher average years of experience.
Intuitively this makes sense as teams will want to select the better
players for the position. Overall, most players were in their first year
of the MLB with 68.2% having 5 or less years of experience. Players with
more years of experience seem to get higher salaries, increasing as
their years of experience.</p>
<pre class="r"><code># Salary by Posiition Group
salaries |&gt;
  mutate(position_group = case_match(simple_position,
                                     c(&quot;rhp&quot;,&quot;lhp&quot;) ~ &quot;pitcher&quot;,
                                     c(&quot;cf&quot;,&quot;lf&quot;,&quot;rf&quot;,&quot;of&quot;) ~ &quot;outfield&quot;,
                                     &quot;dh&quot; ~ &quot;dh&quot;,
                                     .default = &quot;infield&quot;)) |&gt;
  ggplot(aes(x = salary_2022, color = position_group)) +
  geom_density() +
  labs(title = &quot;Salary by Position Group&quot;,
       x = &quot;2022 Salary&quot;,
       y = &quot;&quot;) +
  scale_x_continuous(labels = label_comma()) +
  scale_color_discrete(name = &quot;Position Group&quot;,
                       labels = c(&quot;Designated Hitter&quot;,
                                &quot;Infield&quot;,
                                &quot;Outfield&quot;,
                                &quot;Pitcher&quot;)) +
  theme_bw()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-4-1.png" width="90%" /></p>
<pre class="r"><code># Salary by Experience
salaries %&gt;%
  ggplot(aes(x=factor(floor(service_time_yrs)), y=salary_2022)) +
  geom_boxplot() +
  labs(title = &quot;Salary Distribution for Years of Experience&quot;,
       x = &quot;Years of Experience&quot;,
       y = &quot;&quot;) +
  scale_y_continuous(labels = label_comma()) +
  theme_bw()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-5-1.png" width="90%" /></p>
<pre class="r"><code># Salary by Experience
salaries %&gt;%
  ggplot(aes(x=experience_group, y=salary_2022)) +
  geom_boxplot() +
  labs(title = &quot;Salary Distribution for Years of Experience&quot;,
       x = &quot;Years of Experience&quot;,
       y = &quot;&quot;) +
  scale_y_continuous(labels = label_comma()) +
  theme_bw()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-6-1.png" width="90%" /></p>
<pre class="r"><code># Experience by Position
salaries |&gt;
  ggplot(aes(x = service_time_floor, 
             y = simple_position, 
             fill = simple_position)) + 
  ggridges::geom_density_ridges(alpha = 0.5) +
  labs(title = &quot;Experience by Position&quot;,
       x = &quot;Years of Experience&quot;,
       y = &quot;&quot;) +
  xlim(0,25) +
  scale_y_discrete(labels = c(&quot;1b&quot; = &quot;1st Base&quot;,
                    &quot;2b&quot; = &quot;2nd Base&quot;,
                    &quot;3b&quot; = &quot;3rd Base&quot;,
                    &quot;inf&quot; = &quot;Infield&quot;,
                    &quot;c&quot; = &quot;Catcher&quot;,
                    &quot;rf&quot; = &quot;Right Field&quot;,
                    &quot;lf&quot; = &quot;Left Field&quot;,
                    &quot;cf&quot; = &quot;Center Field&quot;,
                    &quot;of&quot; = &quot;Outfield&quot;,
                    &quot;lhp&quot; = &quot;Left Hand Pitcher&quot;,
                    &quot;rhp&quot; = &quot;Right Hand Pitcher&quot;,
                    &quot;dh&quot; = &quot;Designated Hitter&quot;,
                    &quot;ss&quot; = &quot;Shortstop&quot;)) +
  guides(fill=&quot;none&quot;) +
  theme_bw()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-7-1.png" width="90%" /></p>
</div>
<div id="batting-eda" class="section level3">
<h3>Batting EDA</h3>
<p>Many of the counting statistics for batting are right skewed, as most
players are not hitting multiple home runs in the season. Some of the
advanced statistics such as OPS+ are more normally distributed. An
important idea to keep in mind is that many of these collected
statistics are strongly correlated with each other as the advanced
statistics are often a formula taking input from the counting
statistics. Looking at the relation with salary, it seems that there may
be an association between salary and home runs as well as OPS+.</p>
<pre class="r"><code># Chances at Bat by Home Runs
merged_batting %&gt;%
  ggplot(aes(x = ab,y= hr)) +
  geom_point(aes(color = ops)) +
  geom_smooth(method = lm, se = FALSE, color = &quot;firebrick&quot;) +
  labs(title = &quot;Who is the most &#39;effective&#39; at the plate?&quot;,
       x = &quot;Chances at Bat&quot;,
       y = &quot;Number of Home Runs&quot;) +
  scale_color_continuous(&quot;OPS&quot;) +
  theme_bw()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-8-1.png" width="90%" /></p>
<pre class="r"><code># Corrs for Batting Data
merged_batting |&gt;
  select(hr, ba, ops) |&gt;
  GGally::ggpairs()</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-9-1.png" width="90%" /></p>
<pre class="r"><code># Distributions for Used Statistics
yrsCol = merged_batting |&gt;
  count(experience_group) |&gt;
  ggplot(aes(x = experience_group, y=n)) + 
  geom_col(fill = &#39;blue&#39;, col = &#39;black&#39;) +
  labs(x=&quot;Years of Experience&quot;,y=&quot;&quot;) +
  theme_bw()
hrsHist = merged_batting |&gt;
  ggplot(aes(x = hr)) + 
  geom_histogram(fill = &#39;purple&#39;, col = &#39;black&#39;) +
  labs(x=&quot;Home Runs&quot;,y=&quot;&quot;) +
  theme_bw()
basHist = merged_batting |&gt;
  ggplot(aes(x = ba)) + 
  geom_histogram(fill = &#39;yellow&#39;, col = &#39;black&#39;) +
  labs(x=&quot;Batting Averages&quot;,y=&quot;&quot;) +
  theme_bw()
opsHist = merged_batting |&gt;
  ggplot(aes(x = ops_2)) + 
  geom_histogram(fill = &#39;lightgreen&#39;, col = &#39;black&#39;) +
  labs(x=&quot;OPS+&quot;,y=&quot;&quot;) +
  theme_bw()

dist_patch = (yrsCol+hrsHist)/(basHist+opsHist)

dist_patch + plot_annotation(title = &quot;Distribution of Important Batting Statistics&quot;)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-10-1.png" width="90%" /></p>
<pre class="r"><code># Scatter for Used Statistics
yrs = merged_batting |&gt;
  ggplot(aes(x = experience_group, y = salary_2022)) + 
  geom_boxplot(col = &#39;blue&#39;) +
  labs(x=&quot;Years of Experience&quot;,y=&quot;&quot;) +
  scale_y_continuous(labels = label_comma()) +
  theme_bw()
hrs = merged_batting |&gt;
  ggplot(aes(x = hr, y = salary_2022)) + 
  geom_point(col = &#39;purple&#39;) +
  guides(y=&quot;none&quot;) +
  labs(x=&quot;Home Runs&quot;,y=&quot;&quot;) +
  theme_bw()
bas = merged_batting |&gt;
  ggplot(aes(x = ba, y = salary_2022)) + 
  geom_point(col = &#39;yellow&#39;) +
  labs(x=&quot;Batting Averages&quot;,y=&quot;&quot;) +
  scale_y_continuous(labels = label_comma()) +
  theme_bw()
ops = merged_batting |&gt;
  ggplot(aes(x = ops_2, y = salary_2022)) + 
  geom_point(col = &#39;lightgreen&#39;) +
  guides(y=&quot;none&quot;) +
  labs(x=&quot;OPS+&quot;,y=&quot;&quot;) +
  theme_bw()

scatter_patch = (yrs+hrs)/(bas+ops)

scatter_patch + plot_annotation(title = &quot;Scatterplot of Batting Statistics and Salary&quot;)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-11-1.png" width="90%" /></p>
</div>
<div id="pitching-eda" class="section level3">
<h3>Pitching EDA</h3>
<pre class="r"><code>ip_plot = merged_pitching |&gt; 
  ggplot(aes(x = ip_total)) + 
  geom_histogram(binwidth = 5, fill = &quot;red&quot;, col = &quot;black&quot;) +
  labs(
       x = &quot;Innings Pitched&quot;,
       y = &quot;&quot;) +
  theme_bw()

era_plot = merged_pitching |&gt;
  ggplot(aes(x = era_2)) + 
  geom_histogram(fill = &quot;lightblue&quot;, col = &quot;black&quot;) +
    labs(
       x = &quot;ERA+&quot;,
       y = &quot;&quot;) +
  theme_bw()

bb_plot = merged_pitching |&gt;
  ggplot(aes(x = bb9)) + 
  geom_histogram(fill = &quot;darkgreen&quot;, col = &quot;black&quot;) +
    labs(
       x = &quot;Walks per 9 Innings (BB/9)&quot;,
       y = &quot;&quot;) +
  theme_bw()

so_plot = merged_pitching |&gt;
  ggplot(aes(x = so9)) + 
  geom_histogram(fill = &quot;orange&quot;, col = &quot;black&quot;) +
    labs(
       x = &quot;Strikeouts per 9 Innings (SO/9)&quot;,
       y = &quot;&quot;) +
  guides() +
  theme_bw()

hist_pitch = (ip_plot + era_plot) / (bb_plot + so_plot)
hist_pitch + plot_annotation(title = &quot;Histograms of Pitching Statistics&quot;)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-12-1.png" width="90%" /></p>
<p>The distribution of innings pitched is quite right-skewed, with a
peak around 70 innings pitched. The distribution of ERA+ is right-skewed
as well, with a peak around 100 (the league average) and a small number
of pitchers with an ERA+ above 200. The distributions of BB/9 and SO/9
are mostly symmetric, with peaks around 3 and 9, respectively.</p>
<pre class="r"><code>ip_sal = merged_pitching |&gt; 
  ggplot(aes(x = ip_total, y = salary_2022)) + 
  geom_point(col = &quot;red&quot;) + 
  scale_x_continuous(lim = c(0, 250)) +
  scale_y_continuous(labels = label_comma()) +
  labs(x = &quot;Innings Pitched&quot;,
       y = &quot;&quot;) +
  theme_bw()

era_sal = merged_pitching |&gt; 
  ggplot(aes(x = era_2, y = salary_2022)) + 
  geom_point(col = &quot;lightblue&quot;) +
  scale_x_continuous(lim = c(0, 400)) + 
  scale_y_continuous(labels = label_comma()) +
  labs(x = &quot;ERA+&quot;,
       y = &quot;&quot;) +
    guides(y=&quot;none&quot;) +
  theme_bw()

bb_sal = merged_pitching |&gt; 
  ggplot(aes(x = bb9, y = salary_2022)) + 
  geom_point(col = &quot;darkgreen&quot;) +
  scale_x_continuous(lim = c(0, 10)) + 
  scale_y_continuous(labels = label_comma()) +
   labs(x = &quot;Walks per 9 Innings (BB/9)&quot;,
       y = &quot;&quot;) +
  theme_bw()

so_sal = merged_pitching |&gt; 
  ggplot(aes(x = so9, y = salary_2022)) + 
  geom_point(col = &quot;orange&quot;) +
  scale_x_continuous(lim = c(0, 20)) + 
  scale_y_continuous(labels = label_comma()) +
   labs(x = &quot;Strikeouts Per 9 Innings (SO/9)&quot;,
       y = &quot;&quot;) +
    guides(y=&quot;none&quot;) +
  theme_bw()

scatt_pitch = (ip_sal + era_sal) / (bb_sal + so_sal)
scatt_pitch + plot_annotation(title = &quot;Scatterplots of Pitching Statistics and Salary&quot;)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-13-1.png" width="90%" /></p>
<p>Interestingly, the pitchers with the highest ERA+ often had
considerably lower salaries.</p>
</div>
</div>
<div id="additional-analysis" class="section level1">
<h1>Additional analysis</h1>
<div id="batting-model" class="section level2">
<h2>Batting Model</h2>
<pre class="r"><code>lm_batting = lm(log10(salary_2022) ~ ops_2 + experience_group,
                 data = merged_batting)

summary(lm_batting)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log10(salary_2022) ~ ops_2 + experience_group, data = merged_batting)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.95350 -0.18334 -0.02296  0.21119  1.09670 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              5.5217232  0.0669508  82.474  &lt; 2e-16 ***
## ops_2                    0.0043860  0.0006429   6.823 3.93e-11 ***
## experience_group3+ years 0.8509329  0.0376350  22.610  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3432 on 351 degrees of freedom
##   (44 observations deleted due to missingness)
## Multiple R-squared:  0.6228, Adjusted R-squared:  0.6207 
## F-statistic: 289.8 on 2 and 351 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>plot(residuals(lm_batting) ~ fitted.values(lm_batting), 
     main = &quot;Residuals vs. Fitted Values Plot for Batting Model&quot;,
     xlab = &quot;Fitted Values&quot;,
     ylab = &quot;Residuals&quot;)
abline(h = 0)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-15-1.png" width="90%" /></p>
<pre class="r"><code>qqnorm(residuals(lm_batting),
       main = &quot;Normal Q-Q Plot for Batting Model&quot;)
qqline(residuals(lm_batting))</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-16-1.png" width="90%" /></p>
<p>We decided to log-transform the salary variable because it is heavily
right-skewed, and decided to use <span
class="math inline">\(log_{10}\)</span> instead of <span
class="math inline">\(ln\)</span> for the sake of interpretability. We
included OPS+, the “all-in-one” measure of hitter performance as well as
their number of years of experience.</p>
<p>From our model, we can see that batters with more experience have
higher salaries, even adjusting for performance. At the same time,
adjusting for service time, batters with higher OPS+ (that is, batters
who perform better) have significantly higher salaries.</p>
<p>Based on this model, which player provided the best value for money?
Who was most cost effective? That would be the player with a high OPS+
and the lowest residual, indicating that their actual salary was lower
than predicted based on their performance.</p>
<div id="top-5-batters-by-value" class="section level3">
<h3>Top 5 Batters by Value</h3>
<pre class="r"><code>merged_batting |&gt;
  modelr::add_predictions(lm_batting) |&gt;
  modelr::add_residuals(lm_batting) |&gt;
  arrange(resid) |&gt;
  select(name, salary_2022, service_time_floor, experience_group, ops_2, pred, resid ) |&gt;
  mutate(expected_salary = 10^pred) |&gt;
  slice(1:5)</code></pre>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="15%" />
<col width="11%" />
<col width="17%" />
<col width="16%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">salary_2022</th>
<th align="right">service_time_floor</th>
<th align="left">experience_group</th>
<th align="right">ops_2</th>
<th align="right">pred</th>
<th align="right">resid</th>
<th align="right">expected_salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Brandon Drury</td>
<td align="right">900000</td>
<td align="right">5</td>
<td align="left">3+ years</td>
<td align="right">122</td>
<td align="right">6.907744</td>
<td align="right">-0.9535020</td>
<td align="right">8086200</td>
</tr>
<tr class="even">
<td align="left">Luke Maile</td>
<td align="right">900000</td>
<td align="right">4</td>
<td align="left">3+ years</td>
<td align="right">82</td>
<td align="right">6.732306</td>
<td align="right">-0.7780632</td>
<td align="right">5398905</td>
</tr>
<tr class="odd">
<td align="left">Kyle Higashioka</td>
<td align="right">935000</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">85</td>
<td align="right">6.745464</td>
<td align="right">-0.7746520</td>
<td align="right">5564980</td>
</tr>
<tr class="even">
<td align="left">Dylan Moore</td>
<td align="right">1350000</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">121</td>
<td align="right">6.903359</td>
<td align="right">-0.7730247</td>
<td align="right">8004948</td>
</tr>
<tr class="odd">
<td align="left">Colin Moran</td>
<td align="right">1000000</td>
<td align="right">4</td>
<td align="left">3+ years</td>
<td align="right">85</td>
<td align="right">6.745464</td>
<td align="right">-0.7454636</td>
<td align="right">5564980</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="top-10-batters-by-salary" class="section level3">
<h3>Top 10 Batters by Salary</h3>
<pre class="r"><code>merged_batting |&gt;
  modelr::add_predictions(lm_batting) |&gt;
  modelr::add_residuals(lm_batting) |&gt;
  arrange(desc(salary_2022)) |&gt;
  select(name, salary_2022, service_time_floor,experience_group, ops_2, pred, resid ) |&gt;
  mutate(expected_salary = 10^pred) |&gt;
  slice(1:10)</code></pre>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="11%" />
<col width="17%" />
<col width="16%" />
<col width="5%" />
<col width="8%" />
<col width="9%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">salary_2022</th>
<th align="right">service_time_floor</th>
<th align="left">experience_group</th>
<th align="right">ops_2</th>
<th align="right">pred</th>
<th align="right">resid</th>
<th align="right">expected_salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mike Trout</td>
<td align="right">37116667</td>
<td align="right">10</td>
<td align="left">3+ years</td>
<td align="right">176</td>
<td align="right">7.144587</td>
<td align="right">0.4249821</td>
<td align="right">13950407</td>
</tr>
<tr class="even">
<td align="left">Anthony Rendon</td>
<td align="right">36571429</td>
<td align="right">8</td>
<td align="left">3+ years</td>
<td align="right">100</td>
<td align="right">6.811253</td>
<td align="right">0.7518888</td>
<td align="right">6475199</td>
</tr>
<tr class="odd">
<td align="left">Carlos Correa</td>
<td align="right">35100000</td>
<td align="right">6</td>
<td align="left">3+ years</td>
<td align="right">137</td>
<td align="right">6.973534</td>
<td align="right">0.5717731</td>
<td align="right">9408796</td>
</tr>
<tr class="even">
<td align="left">Manny Machado</td>
<td align="right">34000000</td>
<td align="right">9</td>
<td align="left">3+ years</td>
<td align="right">158</td>
<td align="right">7.065639</td>
<td align="right">0.4658395</td>
<td align="right">11631599</td>
</tr>
<tr class="odd">
<td align="left">Corey Seager</td>
<td align="right">33000000</td>
<td align="right">6</td>
<td align="left">3+ years</td>
<td align="right">117</td>
<td align="right">6.885815</td>
<td align="right">0.6326993</td>
<td align="right">7688022</td>
</tr>
<tr class="even">
<td align="left">Nolan Arenado</td>
<td align="right">32974847</td>
<td align="right">8</td>
<td align="left">3+ years</td>
<td align="right">151</td>
<td align="right">7.034938</td>
<td align="right">0.4832452</td>
<td align="right">10837712</td>
</tr>
<tr class="odd">
<td align="left">Francisco Lindor</td>
<td align="right">32477277</td>
<td align="right">6</td>
<td align="left">3+ years</td>
<td align="right">126</td>
<td align="right">6.925288</td>
<td align="right">0.5862912</td>
<td align="right">8419540</td>
</tr>
<tr class="even">
<td align="left">Miguel Cabrera</td>
<td align="right">32000000</td>
<td align="right">18</td>
<td align="left">3+ years</td>
<td align="right">81</td>
<td align="right">6.727920</td>
<td align="right">0.7772303</td>
<td align="right">5344655</td>
</tr>
<tr class="odd">
<td align="left">George Springer</td>
<td align="right">29666667</td>
<td align="right">7</td>
<td align="left">3+ years</td>
<td align="right">133</td>
<td align="right">6.955990</td>
<td align="right">0.5162786</td>
<td align="right">9036290</td>
</tr>
<tr class="even">
<td align="left">Jose Altuve</td>
<td align="right">29200000</td>
<td align="right">10</td>
<td align="left">3+ years</td>
<td align="right">161</td>
<td align="right">7.078797</td>
<td align="right">0.3865855</td>
<td align="right">11989397</td>
</tr>
</tbody>
</table>
</div>
<p>It looks like in 2022, the most cost-effective player was Albert
Pujols, who made $2.5 million in his 21st season with an OPS+ of
151.</p>
</div>
</div>
<div id="pitching-model" class="section level2">
<h2>Pitching Model</h2>
<pre class="r"><code>lm_pitching = lm(log10(salary_2022) ~ hand + pitcher_type + hand*pitcher_type + ip_total + era_2 + bb9 + so9 + experience_group,
                 data = merged_pitching)

summary(lm_pitching)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log10(salary_2022) ~ hand + pitcher_type + hand * 
##     pitcher_type + ip_total + era_2 + bb9 + so9 + experience_group, 
##     data = merged_pitching)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.7256 -0.1353  0.0000  0.1118  0.9380 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               6.5815420  0.3024707  21.759  &lt; 2e-16 ***
## handrhp                  -0.4242111  0.3054319  -1.389 0.165624    
## pitcher_typer            -0.8528043  0.2839805  -3.003 0.002838 ** 
## pitcher_types            -0.5941512  0.2867592  -2.072 0.038898 *  
## ip_total                  0.0014225  0.0003437   4.139 4.24e-05 ***
## era_2                    -0.0004776  0.0002877  -1.660 0.097707 .  
## bb9                      -0.0377370  0.0128069  -2.947 0.003397 ** 
## so9                       0.0247501  0.0072925   3.394 0.000756 ***
## experience_group3+ years  0.6080049  0.0299496  20.301  &lt; 2e-16 ***
## handrhp:pitcher_typer     0.4144199  0.3072509   1.349 0.178149    
## handrhp:pitcher_types     0.3405457  0.3101460   1.098 0.272844    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2786 on 408 degrees of freedom
##   (50 observations deleted due to missingness)
## Multiple R-squared:  0.677,  Adjusted R-squared:  0.6691 
## F-statistic: 85.52 on 10 and 408 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>plot(residuals(lm_pitching) ~ fitted.values(lm_pitching),
     main = &quot;Residuals vs. Fitted Values Plot for Pitching Model&quot;,
     xlab = &quot;Fitted Values&quot;,
     ylab = &quot;Residuals&quot;)
abline(h = 0)</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-20-1.png" width="90%" /></p>
<pre class="r"><code>qqnorm(residuals(lm_pitching),
       main = &quot;Normal Q-Q Plot for Pitching Model&quot;)
qqline(residuals(lm_pitching))</code></pre>
<p><img src="Final_Report_Draft_files/figure-html/unnamed-chunk-21-1.png" width="90%" /></p>
<p>We decided to log-transform the salary variable because it is heavily
right-skewed, and decided to use <span
class="math inline">\(log_{10}\)</span> instead of <span
class="math inline">\(ln\)</span> for the sake of interpretability. We
included ERA+, the measure of a pitcher’s ERA relative to the league
average, as well as innings pitched (<code>ip_total</code>), walks per
nine innings (<code>bb9</code>) and strikeouts per nine innings
(<code>so9</code>); we used walks/strikeouts per nine innings since the
total number of walks/strikeouts would be highly correlated with the
number of innings pitched.</p>
<p>We accounted for pitcher handedness (right vs. left) as well as
pitcher type (the default type is a closing pitcher, with relief
pitchers and starting pitchers also included in the model). Finally, we
explored the interaction between handedness and pitcher type to see if
pitcher type affects the relationship between handedness and salary.</p>
<p>From our model, we can see that pitcher handedness and pitcher type
have no significant effect on expected salary. Interestingly, the
<code>era_2</code> predictor, even when accounting for pitcher
handedness, pitcher type, and the number of innings pitched, has an
insignificant <span class="math inline">\(P\)</span>-value, implying
that there is no significant association between one of the most highly
regarded summative statistics for pitching effectiveness and pitcher
salary when accounting for pitcher handedness, pitcher type, innings
pitched, walk and strikeout rates, and service time.</p>
<p>The residuals vs. fitted values plot shows that the residuals are
generally evenly spread out; the straight line on the left side of the
plot represents the large number of MLB players who are still on their
rookie contracts, and therefore have a low fitted value (as they usually
make between $700,000 and $1,000,000 per year, which is quite low by MLB
standards). The Normal Q-Q plot shows that the model’s residuals deviate
only slightly from Normal behavior.</p>
<div id="top-5-pitchers-by-value" class="section level3">
<h3>Top 5 Pitchers by Value</h3>
<pre class="r"><code>merged_pitching |&gt;
  modelr::add_predictions(lm_pitching) |&gt;
  modelr::add_residuals(lm_pitching) |&gt;
  arrange(resid) |&gt;
  select(name, salary_2022, service_time_floor, experience_group, era_2, pred, resid ) |&gt;
  mutate(expected_salary = 10^pred) |&gt;
  slice(1:5)</code></pre>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="15%" />
<col width="11%" />
<col width="17%" />
<col width="16%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">salary_2022</th>
<th align="right">service_time_floor</th>
<th align="left">experience_group</th>
<th align="right">era_2</th>
<th align="right">pred</th>
<th align="right">resid</th>
<th align="right">expected_salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drew Hutchison</td>
<td align="right">800000</td>
<td align="right">4</td>
<td align="left">3+ years</td>
<td align="right">85</td>
<td align="right">6.628671</td>
<td align="right">-0.7255811</td>
<td align="right">4252762</td>
</tr>
<tr class="even">
<td align="left">Ryan Borucki</td>
<td align="right">825000</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">68</td>
<td align="right">6.637406</td>
<td align="right">-0.7209523</td>
<td align="right">4339166</td>
</tr>
<tr class="odd">
<td align="left">Trevor Richards</td>
<td align="right">1000000</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">72</td>
<td align="right">6.668099</td>
<td align="right">-0.6680993</td>
<td align="right">4656926</td>
</tr>
<tr class="even">
<td align="left">Sean Newcomb</td>
<td align="right">900000</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">48</td>
<td align="right">6.603083</td>
<td align="right">-0.6488400</td>
<td align="right">4009429</td>
</tr>
<tr class="odd">
<td align="left">Jeffrey Springs</td>
<td align="right">947500</td>
<td align="right">3</td>
<td align="left">3+ years</td>
<td align="right">150</td>
<td align="right">6.615970</td>
<td align="right">-0.6393911</td>
<td align="right">4130192</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="top-10-pitchers-by-salary" class="section level3">
<h3>Top 10 Pitchers by Salary</h3>
<pre class="r"><code>merged_pitching |&gt;
  modelr::add_predictions(lm_pitching) |&gt;
  modelr::add_residuals(lm_pitching) |&gt;
  arrange(desc(salary_2022)) |&gt;
  select(name, salary_2022, service_time_floor, experience_group, era_2, pred, resid ) |&gt;
  mutate(expected_salary = 10^pred) |&gt;
  slice(1:10)</code></pre>
<div class="kable-table">
<table>
<colgroup>
<col width="16%" />
<col width="11%" />
<col width="17%" />
<col width="15%" />
<col width="5%" />
<col width="8%" />
<col width="9%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">salary_2022</th>
<th align="right">service_time_floor</th>
<th align="left">experience_group</th>
<th align="right">era_2</th>
<th align="right">pred</th>
<th align="right">resid</th>
<th align="right">expected_salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Max Scherzer</td>
<td align="right">43333333</td>
<td align="right">13</td>
<td align="left">3+ years</td>
<td align="right">169</td>
<td align="right">6.845976</td>
<td align="right">0.7908462</td>
<td align="right">7014163</td>
</tr>
<tr class="even">
<td align="left">Gerrit Cole</td>
<td align="right">36000000</td>
<td align="right">8</td>
<td align="left">3+ years</td>
<td align="right">110</td>
<td align="right">6.946254</td>
<td align="right">0.6100489</td>
<td align="right">8835957</td>
</tr>
<tr class="odd">
<td align="left">David Price</td>
<td align="right">32000000</td>
<td align="right">11</td>
<td align="left">3+ years</td>
<td align="right">167</td>
<td align="right">6.702960</td>
<td align="right">0.8021897</td>
<td align="right">5046151</td>
</tr>
<tr class="even">
<td align="left">Jacob deGrom</td>
<td align="right">27257728</td>
<td align="right">7</td>
<td align="left">3+ years</td>
<td align="right">126</td>
<td align="right">6.855482</td>
<td align="right">0.5800073</td>
<td align="right">7169392</td>
</tr>
<tr class="odd">
<td align="left">Zack Wheeler</td>
<td align="right">26000000</td>
<td align="right">8</td>
<td align="left">3+ years</td>
<td align="right">142</td>
<td align="right">6.823685</td>
<td align="right">0.5912886</td>
<td align="right">6663229</td>
</tr>
<tr class="even">
<td align="left">Justin Verlander</td>
<td align="right">25000000</td>
<td align="right">16</td>
<td align="left">3+ years</td>
<td align="right">218</td>
<td align="right">6.835075</td>
<td align="right">0.5628650</td>
<td align="right">6840298</td>
</tr>
<tr class="odd">
<td align="left">Marcus Stroman</td>
<td align="right">25000000</td>
<td align="right">7</td>
<td align="left">3+ years</td>
<td align="right">117</td>
<td align="right">6.756888</td>
<td align="right">0.6410518</td>
<td align="right">5713316</td>
</tr>
<tr class="even">
<td align="left">Patrick Corbin</td>
<td align="right">23416667</td>
<td align="right">9</td>
<td align="left">3+ years</td>
<td align="right">62</td>
<td align="right">6.859146</td>
<td align="right">0.5103788</td>
<td align="right">7230134</td>
</tr>
<tr class="odd">
<td align="left">Madison Bumgarner</td>
<td align="right">21882892</td>
<td align="right">11</td>
<td align="left">3+ years</td>
<td align="right">82</td>
<td align="right">6.834678</td>
<td align="right">0.5054269</td>
<td align="right">6834044</td>
</tr>
<tr class="even">
<td align="left">Carlos Rodon</td>
<td align="right">21500000</td>
<td align="right">6</td>
<td align="left">3+ years</td>
<td align="right">138</td>
<td align="right">6.981582</td>
<td align="right">0.3508561</td>
<td align="right">9584786</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>As MLB salaries continue to rise at exponential rates, it is
important to assess whether the league’s biggest contracts are worth it.
Baseball is currently undergoing an analytics-fueled revolution,
inspired by statisticians such as Bill James and teams such as the 2002
“Moneyball” Oakland A’s, that is drastically changing the way the game
is played and the way in which front offices choose which players to
sign and how to maximize their talent. As a consequence of this
revolution, MLB teams have deemphasized simpler statistics once thought
of as key indicators of performance – such as batting average for
hitters and wins for pitchers – in favor of more complex ones, such as
OPS+ and ERA+, that more thoroughly encapsulate a player’s value to
their team.</p>
<p>We sought to use these advanced statistics in order to explore
whether players with top salaries are truly earning them. We found that
while OPS+ had a significant positive association with salary for
hitters, ERA+ had no significant association with salary for pitchers,
implying that other indicators – specifically service time, innings
pitched, walk rate, and strikeout rate – were stronger predictors of a
player’s salary. The team-building implications of these results are
fascinating, especially with respect to pitchers. If there is little to
no association between a pitcher’s ability to limit runs and their
salary, which kinds of pitchers should teams sign in order to maximize
the value of their contracts?</p>
<p>The top five batters and top five pitchers, by salary below expected,
came from similar demographics: veterans on cheap deals. All ten of
these players had at least nine years’ worth of service time, and only
Albert Pujols, in his 22nd and final season, made more than half of the
average MLB salary in 2022. The implications for team-building based on
these results are clear: instead of spending large amounts on a select
few players, give deals to veterans who may be undervalued by the
market, as they are more likely to produce value than the most expensive
players. The Tampa Bay Rays, a team known for their reluctance to spend
as much as their success, have utilized this strategy quite well, riding
a combination of young players on rookie contracts and veterans let go
by other teams – such as Yandy Diaz, Manuel Margot, Ji-Man Choi, Corey
Kluber, and Jeffrey Springs – to the fifth-highest winning percentage in
MLB (out of 30 teams) over the last 10 seasons.</p>
<p>So, what does this mean for the players who earn top-dollar
contracts? On the pitching side, eight of the top 10 pitchers by salary
recorded an ERA+ above 110, meaning that they were a good deal more
effective at getting outs than the average pitcher. And yet, only one of
them (Justin Verlander, who won the AL Cy Young Award as the AL’s top
pitcher in 2022) had an expected salary that was higher than their
actual salary. In other words, even though many of these pitchers
enjoyed good if not great seasons, their performance was still not quite
strong enough to justify their salaries.</p>
<p>However, these results should be interpreted with some caution, given
the importance of service time with respect to our model’s predicted
salary. For example, since the <code>service_time</code> coefficient of
our pitching model is about 0.091, ten years’ worth of service time
would result in an <span class="math inline">\(0.91\)</span>-unit
increase in the log of salary, or a <span
class="math inline">\(10^{0.91} = 8.13\)</span>-fold increase in salary.
Therefore, veteran pitchers such as Verlander, are much more likely to
be given higher expected salaries by our model than young pitchers, even
if their statistics are strong.</p>
<p>There is an inherent trade-off between including an excluding service
time from our models. For example, the pitching model has an adjusted
<span class="math inline">\(R^2\)</span> of 0.687 with the service time
parameter and 0.337 without it, meaning that adding service time to the
model more than doubles the portion of the variance in salary that can
be explained by the model. However, including service time potentially
undervalues the contributions of young players, almost all of whom are
on cheap contracts, that significantly outperform their salary.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
